"""
Author: YOUR NAME GOES HERE
File: abstractcollection.py
"""

class AbstractCollection(object):
    """An abstract collection implementation."""

    # Constructor
    def __init__(self, sourceCollection = None):
        """Sets the initial state of self, which includes the
        contents of sourceCollection, if it's present."""
        
        if type(self) == AbstractCollection:
            raise NotImplementedError("Cannot create object of type AbstractCollection")
        
        self._size = self._modCount = 0
        if sourceCollection:
            for item in sourceCollection:
                self.add(item)

    # Accessor methods
    def __str__(self):
        """Returns the string representation of self, using []
        as delimiters."""
        return "[" + ", ".join(map(str, self)) + "]"

    def __eq__(self, other):
        """Returns True if self equals other,
        or False otherwise.
        Compares pairs of items in the two sequences
        generated by the iterators on self and other."""
        if self is other: return True
        if type(self) != type(other) or \
           len(self) != len(other):
            return False
        otherIter = iter(other)
        for item in self:
            if item != next(otherIter):
                return False
        return True
    
    def __add__(self, other):
        """Returns a new bag containing the contents
        of self and other."""
        result = type(self)(self)
        for item in other:
            result.add(item)
        return result
    
    
    def __len__(self):
        """Returns the number of items in self."""
        return self._size
    
    def isEmpty(self):
        return self._size == 0

    def getModCount(self):
        """Returns the number of mutations to this collection."""
        return self._modCount

    def incModCount(self):
        """Increments the number of mutations by one."""
        self._modCount += 1

    def resetSizeAndModCount(self):
        """Resets the numbers of items and mutations to 0."""
        self._size = 0
        self._modCount = 0

    def storeCurrentModCount(self):
        """Stores the current mod count to check for mutations in the future"""
        self._previousModCount = self._modCount
    
    def modCountChanged(self):
        """Returns true if the mod count has changed since storeCurrentModCount() has been called"""
        return self._previousModCount != self._modCount
